from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.lib.units import inch


# ============================================================
# UCDS v2.1 — Unified Clinical PDF Engine
# ============================================================

PRIMARY = colors.HexColor("#0f3d91")
PRIMARY_LIGHT = colors.HexColor("#e3edff")
TEXT_MAIN = colors.HexColor("#1a2b49")
TEXT_MUTED = colors.HexColor("#6b7a99")
BORDER = colors.HexColor("#d6e1ec")


# ------------------------------------------------------------
# COVER PAGE
# ------------------------------------------------------------
def draw_cover_page(c, width, height):
    c.setFillColor(PRIMARY)
    c.rect(0, 0, width, height, fill=1, stroke=0)

    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 32)
    c.drawString(80, height - 200, "Cleaning Compliance Report")

    c.setFont("Helvetica", 16)
    c.drawString(80, height - 240, "Clinical-Grade Automated Summary")

    c.setFont("Helvetica", 12)
    c.drawString(80, height - 270, "Generated by Cleaning Compliance System")

    c.showPage()


# ------------------------------------------------------------
# SECTION TITLE
# ------------------------------------------------------------
def section_title(c, text, y):
    c.setFillColor(TEXT_MAIN)
    c.setFont("Helvetica-Bold", 16)
    c.drawString(40, y, text)
    return y - 30


# ------------------------------------------------------------
# SUMMARY BLOCK
# ------------------------------------------------------------
def draw_summary_block(c, y, overall_compliance, total_submissions, top_shift, avg_tasks):
    summary_items = [
        ("Overall Compliance", f"{overall_compliance}%"),
        ("Total Submissions", str(total_submissions)),
        ("Top Shift", top_shift),
        ("Average Tasks Completed", str(avg_tasks)),
    ]

    c.setFont("Helvetica", 12)

    for label, value in summary_items:
        c.setFillColor(TEXT_MUTED)
        c.drawString(40, y, f"{label}:")
        c.setFillColor(PRIMARY)
        c.setFont("Helvetica-Bold", 12)
        c.drawString(200, y, value)
        y -= 20
        c.setFont("Helvetica", 12)

    return y - 10


# ------------------------------------------------------------
# KPI GRID
# ------------------------------------------------------------
def draw_kpi_grid(c, y, width, overall_compliance, total_submissions, top_shift, avg_tasks):
    box_width = (width - 100) / 2
    box_height = 80

    kpis = [
        ("Overall Compliance", f"{overall_compliance}%", PRIMARY),
        ("Total Submissions", str(total_submissions), colors.HexColor("#1abc9c")),
        ("Top Shift", top_shift, PRIMARY),
        ("Avg Tasks Completed", str(avg_tasks), TEXT_MUTED),
    ]

    for i, (title, value, color) in enumerate(kpis):
        col = i % 2
        row = i // 2

        x = 40 + col * (box_width + 20)
        box_y = y - (row * (box_height + 20))

        c.setFillColor(PRIMARY_LIGHT)
        c.roundRect(x, box_y, box_width, box_height, 10, fill=1, stroke=0)

        c.setStrokeColor(BORDER)
        c.roundRect(x, box_y, box_width, box_height, 10, fill=0, stroke=1)

        c.setFillColor(TEXT_MUTED)
        c.setFont("Helvetica-Bold", 11)
        c.drawString(x + 12, box_y + box_height - 24, title)

        c.setFillColor(color)
        c.setFont("Helvetica-Bold", 20)
        c.drawString(x + 12, box_y + box_height - 50, value)

    return box_y - 40


# ------------------------------------------------------------
# CHARTS PAGE
# ------------------------------------------------------------
def draw_charts_page(c, width, height, room_chart, shift_chart, tasks_chart):
    y = height - 100
    y = section_title(c, "Charts Overview", y)

    chart_width = 2.8 * inch
    chart_height = 2.8 * inch

    if room_chart:
        c.drawImage(room_chart, 40, y - chart_height, width=chart_width, height=chart_height)

    if shift_chart:
        c.drawImage(shift_chart, 230, y - chart_height, width=chart_width, height=chart_height)

    if tasks_chart:
        c.drawImage(tasks_chart, 420, y - chart_height, width=chart_width, height=chart_height)

    c.showPage()


# ------------------------------------------------------------
# CLINICAL TABLE LAYOUT (MULTI-PAGE SAFE)
# ------------------------------------------------------------
def draw_table(c, width, height, table_data):
    y = height - 100
    y = section_title(c, "Detailed Room Compliance Table", y)

    col_widths = [80, 100, 100, 100, 120]  # Room, Shift, Staff, Compliance, Timestamp

    # Header
    c.setFillColor(PRIMARY_LIGHT)
    c.rect(40, y - 20, sum(col_widths), 20, fill=1, stroke=0)

    c.setFillColor(TEXT_MAIN)
    c.setFont("Helvetica-Bold", 10)

    headers = ["Room", "Shift", "Staff", "Compliance", "Timestamp"]
    x = 40
    for i, h in enumerate(headers):
        c.drawString(x + 4, y - 14, h)
        x += col_widths[i]

    y -= 30

    # Rows
    c.setFont("Helvetica", 10)

    for row in table_data:
        if y < 80:
            c.showPage()
            y = height - 80

        x = 40
        for i, cell in enumerate(row):
            c.setFillColor(colors.white)
            c.rect(x, y - 18, col_widths[i], 18, fill=1, stroke=1)
            c.setFillColor(TEXT_MAIN)
            c.drawString(x + 4, y - 14, str(cell))
            x += col_widths[i]

        y -= 20

    c.showPage()


# ------------------------------------------------------------
# FOOTER
# ------------------------------------------------------------
def draw_footer(c, width):
    c.setFillColor(TEXT_MUTED)
    c.setFont("Helvetica", 9)
    c.drawCentredString(width / 2, 30, "Generated automatically by Cleaning Compliance System — Internal Use Only")


# ------------------------------------------------------------
# MAIN PDF GENERATOR
# ------------------------------------------------------------
def generate_dashboard_pdf(
    filepath,
    overall_compliance,
    total_submissions,
    top_shift,
    avg_tasks,
    room_chart=None,
    shift_chart=None,
    tasks_chart=None,
    table_data=None
):
    c = canvas.Canvas(filepath, pagesize=letter)
    width, height = letter

    # COVER PAGE
    draw_cover_page(c, width, height)

    # SUMMARY PAGE
    y = height - 100
    y = section_title(c, "Summary Overview", y)
    y = draw_summary_block(c, y, overall_compliance, total_submissions, top_shift, avg_tasks)

    y = section_title(c, "Key Performance Indicators", y)
    y = draw_kpi_grid(c, y, width, overall_compliance, total_submissions, top_shift, avg_tasks)

    draw_footer(c, width)
    c.showPage()

    # CHARTS PAGE
    draw_charts_page(c, width, height, room_chart, shift_chart, tasks_chart)

    # TABLE PAGE(S)
    if table_data:
        draw_table(c, width, height, table_data)

    c.save()
